name: dcgan
params:
  batch_size: 128
  output_height: 32
  output_width: 32
  num_channels: 3
  size_of_latent_vector: 100
  num_g_filters: 64
  num_d_filters: 64
  lr: 0.0002
  beta1: 0.5
  max_epochs: 500
